/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // "Warāqa" palette: paper, ink and one rubric accent. Dark mode is night-reading ink-blue.
        // Names are kept from the old Material-style set so every page re-skins through tokens.
        "background": "#f1ede0",
        "surface": "#f1ede0",
        "surface-bright": "#f9f6ee",
        "surface-dim": "#e0dac4",
        "surface-container-lowest": "#f9f6ee",
        "surface-container-low": "#ece7d6",
        "surface-container": "#e7e1cd",
        "surface-container-high": "#e0dac4",
        "surface-container-highest": "#d8d1b9",
        "surface-variant": "#e3ddc9",
        "surface-tint": "#1d2230",
        "on-background": "#1d2230",
        "on-surface": "#1d2230",
        "on-surface-variant": "#4b5062",
        "primary": "#1d2230",
        "on-primary": "#f1ede0",
        "primary-container": "#2d3550",
        "on-primary-container": "#f1ede0",
        "primary-fixed": "#e8e2d0",
        "primary-fixed-dim": "#c9c3b0",
        "on-primary-fixed": "#1d2230",
        "on-primary-fixed-variant": "#2d3550",
        "inverse-primary": "#e8e2d0",
        "secondary": "#a23a2a",
        "on-secondary": "#ffffff",
        "secondary-container": "#efd8cc",
        "on-secondary-container": "#6b2216",
        "secondary-fixed": "#efd8cc",
        "secondary-fixed-dim": "#d9a898",
        "on-secondary-fixed": "#3d0f07",
        "on-secondary-fixed-variant": "#6b2216",
        "tertiary": "#2f5d8c",
        "tertiary-container": "#2f5d8c",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed": "#d6e3f5",
        "tertiary-fixed-dim": "#8fb6e8",
        "on-tertiary-fixed": "#0c2540",
        "on-tertiary-fixed-variant": "#2f5d8c",
        "outline": "#6b6f7c",
        "outline-variant": "#cdc6b0",
        "error": "#a1261b",
        "on-error": "#ffffff",
        "error-container": "#f6d9d2",
        "on-error-container": "#6b130b",
        "inverse-surface": "#1d2230",
        "inverse-on-surface": "#f1ede0",
        "grade-sahih": "#2d6a4f",
        "grade-hasan": "#2f5d8c",
        "grade-daif": "#8a5a00",
        "grade-fabricated": "#a23a2a",
        "grade-unknown": "#5f6270",
        // Night reading
        "dark-background": "#0f1420",
        "dark-surface": "#0f1420",
        "dark-surface-bright": "#283248",
        "dark-surface-dim": "#0f1420",
        "dark-surface-container-lowest": "#161d2c",
        "dark-surface-container-low": "#131a28",
        "dark-surface-container": "#1a2233",
        "dark-surface-container-high": "#20293c",
        "dark-surface-container-highest": "#283248",
        "dark-surface-variant": "#222b3e",
        "dark-on-background": "#e8e2d0",
        "dark-on-surface": "#e8e2d0",
        "dark-on-surface-variant": "#a9adbb",
        "dark-primary": "#e8e2d0",
        "dark-on-primary": "#0f1420",
        "dark-primary-container": "#c9c3b0",
        "dark-on-primary-container": "#0f1420",
        "dark-primary-fixed": "#e8e2d0",
        "dark-on-primary-fixed": "#0f1420",
        "dark-secondary": "#e8836c",
        "dark-secondary-container": "#4a2219",
        "dark-on-secondary-container": "#f5c3b5",
        "dark-outline": "#7c8397",
        "dark-outline-variant": "#2c3548",
        "dark-error": "#ffb4a9",
        "dark-error-container": "#5c1a12",
        "dark-on-error-container": "#ffd9d3",
        "dark-inverse-surface": "#e8e2d0",
        "dark-inverse-on-surface": "#0f1420",
        "dark-grade-sahih": "#7fcf9f",
        "dark-grade-hasan": "#8fb6e8",
        "dark-grade-daif": "#e0b25a",
        "dark-grade-fabricated": "#e8836c",
        "dark-grade-unknown": "#a9adbb",
      },
      borderRadius: {
        // Cut-paper corners everywhere: one small radius, no pills.
        DEFAULT: "2px",
        sm: "2px",
        md: "3px",
        lg: "3px",
        xl: "4px",
        "2xl": "4px",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max-width": "1200px",
      },
      fontFamily: {
        "display-lg": ["Aref Ruqaa", "Amiri", "serif"],
        "ui-caption": ["IBM Plex Sans Arabic", "system-ui", "sans-serif"],
        "ui-label": ["IBM Plex Sans Arabic", "system-ui", "sans-serif"],
        "body-main": ["IBM Plex Sans Arabic", "system-ui", "sans-serif"],
        "body-arabic": ["Amiri", "Noto Naskh Arabic", "serif"],
        "h1-hadith": ["Amiri", "Noto Naskh Arabic", "serif"],
        "latin-serif": ["Newsreader", "Georgia", "serif"],
      },
      fontSize: {
        "display-lg": ["clamp(2.5rem, 6vw, 3.5rem)", { lineHeight: "1.25", fontWeight: "700" }],
        "ui-caption": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "ui-label": ["15px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-main": ["17px", { lineHeight: "1.8", fontWeight: "400" }],
        "body-arabic": ["28px", { lineHeight: "2", fontWeight: "400" }],
        "h1-hadith": ["26px", { lineHeight: "1.6", fontWeight: "700" }],
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "draw-x": { "0%": { transform: "scaleX(0)" }, "100%": { transform: "scaleX(1)" } },
        "ink-pulse": { "0%, 100%": { opacity: "0.35" }, "50%": { opacity: "0.8" } },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.5s cubic-bezier(0.16, 1, 0.3, 1) both",
        "fade-in": "fade-in 0.25s ease-out both",
        "draw-x": "draw-x 0.7s cubic-bezier(0.16, 1, 0.3, 1) both",
        "ink-pulse": "ink-pulse 1.6s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}
